# Generated by Django 5.1.6 on 2025-02-27 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brandName', models.CharField(max_length=255)),
                ('territories', models.CharField(max_length=255)),
                ('office', models.CharField(max_length=255)),
                ('goodsServices', models.TextField()),
                ('logo', models.ImageField(upload_to='logos/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('caution', 'Caution'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('euipoResults', models.TextField(blank=True)),
                ('wipoResults', models.TextField(blank=True)),
                ('sipoResults', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
