# Generated by Django 5.1.6 on 2025-02-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandcheck',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='brandcheck',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='brandcheck',
            name='brandName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brandcheck',
            name='euipoResults',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandcheck',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandcheck',
            name='goodsServices',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandcheck',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='brandcheck',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logos/'),
        ),
        migrations.AlterField(
            model_name='brandcheck',
            name='sipoResults',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandcheck',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='brandcheck',
            name='territories',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brandcheck',
            name='wipoResults',
            field=models.TextField(blank=True, null=True),
        ),
    ]
