# Generated by Django 5.1.6 on 2025-02-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_brandcheck_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandcheck',
            name='territories',
        ),
    ]
